export const GET_CHECKLIST_REQUEST = "GET_CHECKLIST_REQUEST";
export const GET_CHECKLIST_SUCCESS = "GET_CHECKLIST_SUCCESS";
export const GET_CHECKLIST_FAILED = "GET_CHECKLIST_FAILED";
export const GET_CHECKLIST_RESET = "GET_CHECKLIST_RESET";

export const HIDE_CHECKLIST_REQUEST = "HIDE_CHECKLIST_REQUEST";
export const HIDE_CHECKLIST_SUCCESS = "HIDE_CHECKLIST_SUCCESS";
export const HIDE_CHECKLIST_FAILED = "HIDE_CHECKLIST_FAILED";
export const HIDE_CHECKLIST_RESET = "HIDE_CHECKLIST_RESET";

export const CREATE_CHECKLIST_REQUEST = "CREATE_CHECKLIST_REQUEST";
export const CREATE_CHECKLIST_SUCCESS = "CREATE_CHECKLIST_SUCCESS";
export const CREATE_CHECKLIST_FAILED = "CREATE_CHECKLIST_FAILED";
export const CREATE_CHECKLIST_RESET = "CREATE_CHECKLIST_RESET";

export const DELETE_CHECKLIST_REQUEST = "DELETE_CHECKLIST_REQUEST";
export const DELETE_CHECKLIST_SUCCESS = "DELETE_CHECKLIST_SUCCESS";
export const DELETE_CHECKLIST_FAILED = "DELETE_CHECKLIST_FAILED";
export const DELETE_CHECKLIST_RESET = "DELETE_CHECKLIST_RESET";
