export const GET_COMPANY_REQUEST = 'GET_COMPANY_REQUEST';
export const GET_COMPANY_SUCCESS = 'GET_COMPANY_SUCCESS';
export const GET_COMPANY_FAILED = 'GET_COMPANY_FAILED';
export const GET_COMPANY_RESET = 'GET_COMPANY_RESET';

export const UPDATE_COMPANY_REQUEST = 'UPDATE_COMPANY_REQUEST';
export const UPDATE_COMPANY_SUCCESS = 'UPDATE_COMPANY_SUCCESS';
export const UPDATE_COMPANY_FAILED = 'UPDATE_COMPANY_FAILED';
export const UPDATE_COMPANY_RESET = 'UPDATE_COMPANY_RESET';

export const PAYMENT_COMPANY_REQUEST = 'PAYMENT_COMPANY_REQUEST';
export const PAYMENT_COMPANY_SUCCESS = 'PAYMENT_COMPANY_SUCCESS';
export const PAYMENT_COMPANY_FAILED = 'PAYMENT_COMPANY_FAILED';
export const PAYMENT_COMPANY_RESET = 'PAYMENT_COMPANY_RESET';

export const PRICES_COMPANY_REQUEST = 'PRICES_COMPANY_REQUEST';
export const PRICES_COMPANY_SUCCESS = 'PRICES_COMPANY_SUCCESS';
export const PRICES_COMPANY_FAILED = 'PRICES_COMPANY_FAILED';
export const PRICES_COMPANY_RESET = 'PRICES_COMPANY_RESET';