// --------------------------- IFUs by projectId ---------------------------------

export const FIND_IFUs_BY_PROJECT_REQUEST = "FIND_IFUs_BY_PROJECT_REQUEST";
export const FIND_IFUs_BY_PROJECT_SUCCESS = "FIND_IFUs_BY_PROJECT_SUCCESS";
export const FIND_IFUs_BY_PROJECT_FAILED = "FIND_IFUs_BY_PROJECT_FAILED";
export const FIND_IFUs_BY_PROJECT_RESET = "FIND_IFUs_BY_PROJECT_RESET";

export const CREATE_IFUs_ON_PROJECT_REQUEST = "CREATE_IFUs_ON_PROJECT_REQUEST";
export const CREATE_IFUs_ON_PROJECT_SUCCESS = "CREATE_IFUs_ON_PROJECT_SUCCESS";
export const CREATE_IFUs_ON_PROJECT_FAILED = "CREATE_IFUs_ON_PROJECT_FAILED";
export const CREATE_IFUs_ON_PROJECT_RESET = "CREATE_IFUs_ON_PROJECT_RESET";

// --------------------------- IFUs by productId ---------------------------------

export const ALL_IFUs_REQUEST = "ALL_IFUs_REQUEST";
export const ALL_IFUs_SUCCESS = "ALL_IFUs_SUCCESS";
export const ALL_IFUs_FAILED = "ALL_IFUs_FAILED";
export const ALL_IFUs_RESET = "ALL_IFUs_RESET";

export const ALL_IFU_LANGUES_REQUEST = "ALL_IFU_LANGUES_REQUEST";
export const ALL_IFU_LANGUES_SUCCESS = "ALL_IFU_LANGUES_SUCCESS";
export const ALL_IFU_LANGUES_FAILED = "ALL_IFU_LANGUES_FAILED";
export const ALL_IFU_LANGUES_RESET = "ALL_IFU_LANGUES_RESET";

export const GET_IFU_REQUEST = "GET_IFU_REQUEST";
export const GET_IFU_SUCCESS = "GET_IFU_SUCCESS";
export const GET_IFU_FAILED = "GET_IFU_FAILED";
export const GET_IFU_RESET = "GET_IFU_RESET";

export const FIND_RECEIVED_IFU_REQUEST = "FIND_RECEIVED_IFU_REQUEST";
export const FIND_RECEIVED_IFU_SUCCESS = "FIND_RECEIVED_IFU_SUCCESS";
export const FIND_RECEIVED_IFU_FAILED = "FIND_RECEIVED_IFU_FAILED";
export const FIND_RECEIVED_IFU_RESET = "FIND_RECEIVED_IFU_RESET";

export const CREATE_IFU_REQUEST = "CREATE_IFU_REQUEST";
export const CREATE_IFU_SUCCESS = "CREATE_IFU_SUCCESS";
export const CREATE_IFU_FAILED = "CREATE_IFU_FAILED";
export const CREATE_IFU_RESET = "CREATE_IFU_RESET";

export const SEND_TO_APPROVER_REQUEST = "SEND_TO_APPROVER_REQUEST";
export const SEND_TO_APPROVER_SUCCESS = "SEND_TO_APPROVER_SUCCESS";
export const SEND_TO_APPROVER_FAILED = "SEND_TO_APPROVER_FAILED";
export const SEND_TO_APPROVER_RESET = "SEND_TO_APPROVER_RESET";

export const APPROVE_IFU_REQUEST = "APPROVE_IFU_REQUEST";
export const APPROVE_IFU_SUCCESS = "APPROVE_IFU_SUCCESS";
export const APPROVE_IFU_FAILED = "APPROVE_IFU_FAILED";
export const APPROVE_IFU_RESET = "APPROVE_IFU_RESET";

export const SEND_TO_RELEASER_REQUEST = "SEND_TO_RELEASER_REQUEST";
export const SEND_TO_RELEASER_SUCCESS = "SEND_TO_RELEASER_SUCCESS";
export const SEND_TO_RELEASER_FAILED = "SEND_TO_RELEASER_FAILED";
export const SEND_TO_RELEASER_RESET = "SEND_TO_RELEASER_RESET";

export const RELEASE_IFU_REQUEST = "RELEASE_IFU_REQUEST";
export const RELEASE_IFU_SUCCESS = "RELEASE_IFU_SUCCESS";
export const RELEASE_IFU_FAILED = "RELEASE_IFU_FAILED";
export const RELEASE_IFU_RESET = "RELEASE_IFU_RESET";

export const DRAFT_IFU_REQUEST = "DRAFT_IFU_REQUEST";
export const DRAFT_IFU_SUCCESS = "DRAFT_IFU_SUCCESS";
export const DRAFT_IFU_FAILED = "DRAFT_IFU_FAILED";
export const DRAFT_IFU_RESET = "DRAFT_IFU_RESET";

export const APPROVED_IFU_REQUEST = "APPROVED_IFU_REQUEST";
export const APPROVED_IFU_SUCCESS = "APPROVED_IFU_SUCCESS";
export const APPROVED_IFU_FAILED = "APPROVED_IFU_FAILED";
export const APPROVED_IFU_RESET = "APPROVED_IFU_RESET";

export const REJECTED_IFU_REQUEST = "REJECTED_IFU_REQUEST";
export const REJECTED_IFU_SUCCESS = "REJECTED_IFU_SUCCESS";
export const REJECTED_IFU_FAILED = "REJECTED_IFU_FAILED";
export const REJECTED_IFU_RESET = "REJECTED_IFU_RESET";

export const EDIT_IFU_REQUEST = "EDIT_IFU_REQUEST";
export const EDIT_IFU_SUCCESS = "EDIT_IFU_SUCCESS";
export const EDIT_IFU_FAILED = "EDIT_IFU_FAILED";
export const EDIT_IFU_RESET = "EDIT_IFU_RESET";

export const UPDATE_IFU_REQUEST = "UPDATE_IFU_REQUEST";
export const UPDATE_IFU_SUCCESS = "UPDATE_IFU_SUCCESS";
export const UPDATE_IFU_FAILED = "UPDATE_IFU_FAILED";
export const UPDATE_IFU_RESET = "UPDATE_IFU_RESET";

export const FIND_ALL_IFU_REQUEST = "FIND_ALL_IFU_REQUEST";
export const FIND_ALL_IFU_SUCCESS = "FIND_ALL_IFU_SUCCESS";
export const FIND_ALL_IFU_FAILED = "FIND_ALL_IFU_FAILED";
export const FIND_ALL_IFU_RESET = "FIND_ALL_IFU_RESET";

export const FIND_PUBLIC_IFU_REQUEST = "FIND_PUBLIC_IFU_REQUEST";
export const FIND_PUBLIC_IFU_SUCCESS = "FIND_PUBLIC_IFU_SUCCESS";
export const FIND_PUBLIC_IFU_FAILED = "FIND_PUBLIC_IFU_FAILED";
export const FIND_PUBLIC_IFU_RESET = "FIND_PUBLIC_IFU_RESET";
