export const ALL_LABELS_REQUEST = 'ALL_LABELS_REQUEST';
export const ALL_LABELS_SUCCESS = 'ALL_LABELS_SUCCESS';
export const ALL_LABELS_FAILED = 'ALL_LABELS_FAILED';
export const ALL_LABELS_RESET = 'ALL_LABELS_RESET';

export const GET_LABEL_REQUEST = 'GET_LABEL_REQUEST';
export const GET_LABEL_SUCCESS = 'GET_LABEL_SUCCESS';
export const GET_LABEL_FAILED = 'GET_LABEL_FAILED';
export const GET_LABEL_RESET = 'GET_LABEL_RESET';

export const CREATE_LABEL_REQUEST = 'CREATE_LABEL_REQUEST';
export const CREATE_LABEL_SUCCESS = 'CREATE_LABEL_SUCCESS';
export const CREATE_LABEL_FAILED = 'CREATE_LABEL_FAILED';
export const CREATE_LABEL_RESET = 'CREATE_LABEL_RESET';