export const ALL_LABELS_REQUEST = 'ALL_LABELS_REQUEST';
export const ALL_LABELS_SUCCESS = 'ALL_LABELS_SUCCESS';
export const ALL_LABELS_FAILED = 'ALL_LABELS_FAILED';
export const ALL_LABELS_RESET = 'ALL_LABELS_RESET';

export const GET_LABEL_REQUEST = 'GET_LABEL_REQUEST';
export const GET_LABEL_SUCCESS = 'GET_LABEL_SUCCESS';
export const GET_LABEL_FAILED = 'GET_LABEL_FAILED';
export const GET_LABEL_RESET = 'GET_LABEL_RESET';

export const CREATE_LABEL_REQUEST = 'CREATE_LABEL_REQUEST';
export const CREATE_LABEL_SUCCESS = 'CREATE_LABEL_SUCCESS';
export const CREATE_LABEL_FAILED = 'CREATE_LABEL_FAILED';
export const CREATE_LABEL_RESET = 'CREATE_LABEL_RESET';


export const SEND_TO_APPROVER_REQUEST = 'SEND_TO_APPROVER_REQUEST';
export const SEND_TO_APPROVER_SUCCESS = 'SEND_TO_APPROVER_SUCCESS';
export const SEND_TO_APPROVER_FAILED = 'SEND_TO_APPROVER_FAILED';
export const SEND_TO_APPROVER_RESET = 'SEND_TO_APPROVER_RESET';

export const APPROVE_LABEL_REQUEST = 'APPROVE_LABEL_REQUEST';
export const APPROVE_LABEL_SUCCESS = 'APPROVE_LABEL_SUCCESS';
export const APPROVE_LABEL_FAILED = 'APPROVE_LABEL_FAILED';
export const APPROVE_LABEL_RESET = 'APPROVE_LABEL_RESET';

export const SEND_TO_RELEASER_REQUEST = 'SEND_TO_RELEASER_REQUEST';
export const SEND_TO_RELEASER_SUCCESS = 'SEND_TO_RELEASER_SUCCESS';
export const SEND_TO_RELEASER_FAILED = 'SEND_TO_RELEASER_FAILED';
export const SEND_TO_RELEASER_RESET = 'SEND_TO_RELEASER_RESET';

export const RELEASE_LABEL_REQUEST = 'RELEASE_LABEL_REQUEST';
export const RELEASE_LABEL_SUCCESS = 'RELEASE_LABEL_SUCCESS';
export const RELEASE_LABEL_FAILED = 'RELEASE_LABEL_FAILED';
export const RELEASE_LABEL_RESET = 'RELEASE_LABEL_RESET';

export const DRAFT_LABEL_REQUEST = 'DRAFT_LABEL_REQUEST';
export const DRAFT_LABEL_SUCCESS = 'DRAFT_LABEL_SUCCESS';
export const DRAFT_LABEL_FAILED = 'DRAFT_LABEL_FAILED';
export const DRAFT_LABEL_RESET = 'DRAFT_LABEL_RESET';

export const APPROVED_LABEL_REQUEST = 'APPROVED_LABEL_REQUEST';
export const APPROVED_LABEL_SUCCESS = 'APPROVED_LABEL_SUCCESS';
export const APPROVED_LABEL_FAILED = 'APPROVED_LABEL_FAILED';
export const APPROVED_LABEL_RESET = 'APPROVED_LABEL_RESET';

export const REJECTED_LABEL_REQUEST = 'REJECTED_LABEL_REQUEST';
export const REJECTED_LABEL_SUCCESS = 'REJECTED_LABEL_SUCCESS';
export const REJECTED_LABEL_FAILED = 'REJECTED_LABEL_FAILED';
export const REJECTED_LABEL_RESET = 'REJECTED_LABEL_RESET';

export const SAVE_ORDER_LABEL_REQUEST = 'SAVE_ORDER_LABEL_REQUEST';
export const SAVE_ORDER_LABEL_SUCCESS = 'SAVE_ORDER_LABEL_SUCCESS';
export const SAVE_ORDER_LABEL_FAILED = 'SAVE_ORDER_LABEL_FAILED';
export const SAVE_ORDER_LABEL_RESET = 'SAVE_ORDER_LABEL_RESET';

export const GET_TEMPLATES_REQUEST = 'GET_TEMPLATES_REQUEST';
export const GET_TEMPLATES_SUCCESS = 'GET_TEMPLATES_SUCCESS';
export const GET_TEMPLATES_FAILED = 'GET_TEMPLATES_FAILED';
export const GET_TEMPLATES_RESET = 'GET_TEMPLATES_RESET';

export const TO_PRINT_LABEL_REQUEST = 'TO_PRINT_LABEL_REQUEST';
export const TO_PRINT_LABEL_SUCCESS = 'TO_PRINT_LABEL_SUCCESS';
export const TO_PRINT_LABEL_FAILED = 'TO_PRINT_LABEL_FAILED';
export const TO_PRINT_LABEL_RESET = 'TO_PRINT_LABEL_RESET';

export const LABEL_LOGS_REQUEST = 'LABEL_LOGS_REQUEST';
export const LABEL_LOGS_SUCCESS = 'LABEL_LOGS_SUCCESS';
export const LABEL_LOGS_FAILED = 'LABEL_LOGS_FAILED';
export const LABEL_LOGS_RESET = 'LABEL_LOGS_RESET';

export const LOT_GENERATOR_REQUEST = 'LOT_GENERATOR_REQUEST';
export const LOT_GENERATOR_SUCCESS = 'LOT_GENERATOR_SUCCESS';
export const LOT_GENERATOR_FAILED = 'LOT_GENERATOR_FAILED';
export const LOT_GENERATOR_RESET = 'LOT_GENERATOR_RESET';