export const ALL_LABELS_REQUEST = 'ALL_LABELS_REQUEST';
export const ALL_LABELS_SUCCESS = 'ALL_LABELS_SUCCESS';
export const ALL_LABELS_FAILED = 'ALL_LABELS_FAILED';
export const ALL_LABELS_RESET = 'ALL_LABELS_RESET';

export const GET_LABEL_REQUEST = 'GET_LABEL_REQUEST';
export const GET_LABEL_SUCCESS = 'GET_LABEL_SUCCESS';
export const GET_LABEL_FAILED = 'GET_LABEL_FAILED';
export const GET_LABEL_RESET = 'GET_LABEL_RESET';

export const CREATE_LABEL_REQUEST = 'CREATE_LABEL_REQUEST';
export const CREATE_LABEL_SUCCESS = 'CREATE_LABEL_SUCCESS';
export const CREATE_LABEL_FAILED = 'CREATE_LABEL_FAILED';
export const CREATE_LABEL_RESET = 'CREATE_LABEL_RESET';


export const SEND_TO_APPROVER_REQUEST = 'SEND_TO_APPROVER_REQUEST';
export const SEND_TO_APPROVER_SUCCESS = 'SEND_TO_APPROVER_SUCCESS';
export const SEND_TO_APPROVER_FAILED = 'SEND_TO_APPROVER_FAILED';
export const SEND_TO_APPROVER_RESET = 'SEND_TO_APPROVER_RESET';

export const APPROVE_LABEL_REQUEST = 'APPROVE_LABEL_REQUEST';
export const APPROVE_LABEL_SUCCESS = 'APPROVE_LABEL_SUCCESS';
export const APPROVE_LABEL_FAILED = 'APPROVE_LABEL_FAILED';
export const APPROVE_LABEL_RESET = 'APPROVE_LABEL_RESET';

export const SEND_TO_RELEASER_REQUEST = 'SEND_TO_RELEASER_REQUEST';
export const SEND_TO_RELEASER_SUCCESS = 'SEND_TO_RELEASER_SUCCESS';
export const SEND_TO_RELEASER_FAILED = 'SEND_TO_RELEASER_FAILED';
export const SEND_TO_RELEASER_RESET = 'SEND_TO_RELEASER_RESET';

export const RELEASE_LABEL_REQUEST = 'RELEASE_LABEL_REQUEST';
export const RELEASE_LABEL_SUCCESS = 'RELEASE_LABEL_SUCCESS';
export const RELEASE_LABEL_FAILED = 'RELEASE_LABEL_FAILED';
export const RELEASE_LABEL_RESET = 'RELEASE_LABEL_RESET';