export const PRODUCTS_REQUEST = 'PRODUCTS_REQUEST';
export const PRODUCTS_SUCCESS = 'PRODUCTS_SUCCESS';
export const PRODUCTS_FAILED = 'PRODUCTS_FAILED';
export const PRODUCTS_RESET = 'PRODUCTS_RESET';

export const PRODUCT_BY_ID_REQUEST = 'PRODUCT_BY_ID_REQUEST';
export const PRODUCT_BY_ID_SUCCESS = 'PRODUCT_BY_ID_SUCCESS';
export const PRODUCT_BY_ID_FAILED = 'PRODUCT_BY_ID_FAILED';
export const PRODUCT_BY_ID_RESET = 'PRODUCT_BY_ID_RESET';

export const CREATE_PRODUCT_REQUEST = 'CREATE_PRODUCT_REQUEST';
export const CREATE_PRODUCT_SUCCESS = 'CREATE_PRODUCT_SUCCESS';
export const CREATE_PRODUCT_FAILED = 'CREATE_PRODUCT_FAILED';
export const CREATE_PRODUCT_RESET = 'CREATE_PRODUCT_RESET';