export const ALL_PROJECTS_REQUEST = 'ALL_PROJECTS_REQUEST';
export const ALL_PROJECTS_SUCCESS = 'ALL_PROJECTS_SUCCESS';
export const ALL_PROJECTS_FAILED = 'ALL_PROJECTS_FAILED';
export const ALL_PROJECTS_RESET = 'ALL_PROJECTS_RESET';

export const GET_PROJECT_REQUEST = 'GET_PROJECT_REQUEST';
export const GET_PROJECT_SUCCESS = 'GET_PROJECT_SUCCESS';
export const GET_PROJECT_FAILED = 'GET_PROJECT_FAILED';
export const GET_PROJECT_RESET = 'GET_PROJECT_RESET';

export const START_PROJECT_REQUEST = 'START_PROJECT_REQUEST';
export const START_PROJECT_SUCCESS = 'START_PROJECT_SUCCESS';
export const START_PROJECT_FAILED = 'START_PROJECT_FAILED';
export const START_PROJECT_RESET = 'START_PROJECT_RESET';

export const DELETE_PROJECT_REQUEST = 'DELETE_PROJECT_REQUEST';
export const DELETE_PROJECT_SUCCESS = 'DELETE_PROJECT_SUCCESS';
export const DELETE_PROJECT_FAILED = 'DELETE_PROJECT_FAILED';
export const DELETE_PROJECT_RESET = 'DELETE_PROJECT_RESET';

export const MANUFACTURER_INFORMATION_REQUEST = 'MANUFACTURER_INFORMATION_REQUEST';
export const MANUFACTURER_INFORMATION_SUCCESS = 'MANUFACTURER_INFORMATION_SUCCESS';
export const MANUFACTURER_INFORMATION_FAILED = 'MANUFACTURER_INFORMATION_FAILED';
export const MANUFACTURER_INFORMATION_RESET = 'MANUFACTURER_INFORMATION_RESET';

export const LEGISLATION_REQUEST = 'LEGISLATION_REQUEST';
export const LEGISLATION_SUCCESS = 'LEGISLATION_SUCCESS';
export const LEGISLATION_FAILED = 'LEGISLATION_FAILED';
export const LEGISLATION_RESET = 'LEGISLATION_RESET';

export const PRODUCT_INFORMATION_REQUEST =  'PRODUCT_INFORMATION_REQUEST';
export const PRODUCT_INFORMATION_SUCCESS =  'PRODUCT_INFORMATION_SUCCESS';
export const PRODUCT_INFORMATION_FAILED =  'PRODUCT_INFORMATION_FAILED';
export const PRODUCT_INFORMATION_RESET = 'PRODUCT_INFORMATION_RESET';

export const STORAGE_REQUEST =  'STORAGE_REQUEST';
export const STORAGE_SUCCESS =  'STORAGE_SUCCESS';
export const STORAGE_FAILED =  'STORAGE_FAILED';
export const STORAGE_RESET = 'STORAGE_RESET';

export const STERILITY_REQUEST =  'STERILITY_REQUEST';
export const STERILITY_SUCCESS =  'STERILITY_SUCCESS';
export const STERILITY_FAILED =  'STERILITY_FAILED';
export const STERILITY_RESET = 'STERILITY_RESET';

export const SAFE_USE_REQUEST =  'SAFE_USE_REQUEST';
export const SAFE_USE_SUCCESS =  'SAFE_USE_SUCCESS';
export const SAFE_USE_FAILED =  'SAFE_USE_FAILED';
export const SAFE_USE_RESET = 'SAFE_USE_RESET';

export const TRANSFUSION_INFUSION_REQUEST =  'TRANSFUSION_INFUSION_REQUEST';
export const TRANSFUSION_INFUSION_SUCCESS =  'TRANSFUSION_INFUSION_SUCCESS';
export const TRANSFUSION_INFUSION_FAILED =  'TRANSFUSION_INFUSION_FAILED';
export const TRANSFUSION_INFUSION_RESET = 'TRANSFUSION_INFUSION_RESET';

export const IVD_DIAGNOSTIC_REQUEST =  'IVD_DIAGNOSTIC_REQUEST';
export const IVD_DIAGNOSTIC_SUCCESS =  'IVD_DIAGNOSTIC_SUCCESS';
export const IVD_DIAGNOSTIC_FAILED =  'IVD_DIAGNOSTIC_FAILED';
export const IVD_DIAGNOSTIC_RESET = 'IVD_DIAGNOSTIC_RESET';

export const OTHERS_REQUEST =  'OTHERS_REQUEST';
export const OTHERS_SUCCESS =  'OTHERS_SUCCESS';
export const OTHERS_FAILED =  'OTHERS_FAILED';
export const OTHERS_RESET = 'OTHERS_RESET';

export const SENDING_PROJECT_REQUEST =  'SENDING_PROJECT_REQUEST';
export const SENDING_PROJECT_SUCCESS =  'SENDING_PROJECT_SUCCESS';
export const SENDING_PROJECT_FAILED =  'SENDING_PROJECT_FAILED';
export const SENDING_PROJECT_RESET = 'SENDING_PROJECT_RESET';

export const ROLE_PROJECT_REQUEST =  'ROLE_PROJECT_REQUEST';
export const ROLE_PROJECT_SUCCESS =  'ROLE_PROJECT_SUCCESS';
export const ROLE_PROJECT_FAILED =  'ROLE_PROJECT_FAILED';
export const ROLE_PROJECT_RESET = 'ROLE_PROJECT_RESET';

export const RELEASED_PROJECT_REQUEST =  'RELEASED_PROJECT_REQUEST';
export const RELEASED_PROJECT_SUCCESS =  'RELEASED_PROJECT_SUCCESS';
export const RELEASED_PROJECT_FAILED =  'RELEASED_PROJECT_FAILED';
export const RELEASED_PROJECT_RESET = 'RELEASED_PROJECT_RESET';

export const RELEASE_PROJECT_REQUEST =  'RELEASE_PROJECT_REQUEST';
export const RELEASE_PROJECT_SUCCESS =  'RELEASE_PROJECT_SUCCESS';
export const RELEASE_PROJECT_FAILED =  'RELEASE_PROJECT_FAILED';
export const RELEASE_PROJECT_RESET = 'RELEASE_PROJECT_RESET';

export const DOCUMENT_REQUEST =  'DOCUMENT_REQUEST';
export const DOCUMENT_SUCCESS =  'DOCUMENT_SUCCESS';
export const DOCUMENT_FAILED =  'DOCUMENT_FAILED';
export const DOCUMENT_RESET = 'DOCUMENT_RESET';

export const DOCUMENTS_REQUEST =  'DOCUMENTS_REQUEST';
export const DOCUMENTS_SUCCESS =  'DOCUMENTS_SUCCESS';
export const DOCUMENTS_FAILED =  'DOCUMENTS_FAILED';
export const DOCUMENTS_RESET = 'DOCUMENTS_RESET';

export const DELETE_DOCUMENTS_REQUEST =  'DELETE_DOCUMENTS_REQUEST';
export const DELETE_DOCUMENTS_SUCCESS =  'DELETE_DOCUMENTS_SUCCESS';
export const DELETE_DOCUMENTS_FAILED =  'DELETE_DOCUMENTS_FAILED';
export const DELETE_DOCUMENTS_RESET = 'DELETE_DOCUMENTS_RESET';

export const GET_DOCUMENT_REQUEST =  'GET_DOCUMENT_REQUEST';
export const GET_DOCUMENT_SUCCESS =  'GET_DOCUMENT_SUCCESS';
export const GET_DOCUMENT_FAILED =  'GET_DOCUMENT_FAILED';
export const GET_DOCUMENT_RESET = 'GET_DOCUMENT_RESET';