// contact constants
export const CONTACTS_SUPPER_ADMIN_REQUEST = 'CONTACTS_SUPPER_ADMIN_REQUEST';
export const CONTACTS_SUPPER_ADMIN_SUCCESS = 'CONTACTS_SUPPER_ADMIN_SUCCESS';
export const CONTACTS_SUPPER_ADMIN_FAILED = 'CONTACTS_SUPPER_ADMIN_FAILED';
export const CONTACTS_SUPPER_ADMIN_RESET = 'CONTACTS_SUPPER_ADMIN_RESET';

export const GET_CONTACT_SUPPER_ADMIN_REQUEST = 'GET_CONTACT_SUPPER_ADMIN_REQUEST';
export const GET_CONTACT_SUPPER_ADMIN_SUCCESS = 'GET_CONTACT_SUPPER_ADMIN_SUCCESS';
export const GET_CONTACT_SUPPER_ADMIN_FAILED = 'GET_CONTACT_SUPPER_ADMIN_FAILED';
export const GET_CONTACT_SUPPER_ADMIN_RESET = 'GET_CONTACT_SUPPER_ADMIN_RESET';

export const DELETE_CONTACT_SUPPER_ADMIN_REQUEST = 'DELETE_CONTACT_SUPPER_ADMIN_REQUEST';
export const DELETE_CONTACT_SUPPER_ADMIN_SUCCESS = 'DELETE_CONTACT_SUPPER_ADMIN_SUCCESS';
export const DELETE_CONTACT_SUPPER_ADMIN_FAILED = 'DELETE_CONTACT_SUPPER_ADMIN_FAILED';
export const DELETE_CONTACT_SUPPER_ADMIN_RESET = 'DELETE_CONTACT_SUPPER_ADMIN_RESET';

// companies constants
export const COMPANIES_SUPPER_ADMIN_REQUEST = 'COMPANIES_SUPPER_ADMIN_REQUEST';
export const COMPANIES_SUPPER_ADMIN_SUCCESS = 'COMPANIES_SUPPER_ADMIN_SUCCESS';
export const COMPANIES_SUPPER_ADMIN_FAILED = 'COMPANIES_SUPPER_ADMIN_FAILED';
export const COMPANIES_SUPPER_ADMIN_RESET = 'COMPANIES_SUPPER_ADMIN_RESET';

export const GET_COMPANY_SUPPER_ADMIN_REQUEST = 'GET_COMPANY_SUPPER_ADMIN_REQUEST';
export const GET_COMPANY_SUPPER_ADMIN_SUCCESS = 'GET_COMPANY_SUPPER_ADMIN_SUCCESS';
export const GET_COMPANY_SUPPER_ADMIN_FAILED = 'GET_COMPANY_SUPPER_ADMIN_FAILED';
export const GET_COMPANY_SUPPER_ADMIN_RESET = 'GET_COMPANY_SUPPER_ADMIN_RESET';

export const PERMISSION_COMPANY_SUPPER_ADMIN_REQUEST = 'PERMISSION_COMPANY_SUPPER_ADMIN_REQUEST';
export const PERMISSION_COMPANY_SUPPER_ADMIN_SUCCESS = 'PERMISSION_COMPANY_SUPPER_ADMIN_SUCCESS';
export const PERMISSION_COMPANY_SUPPER_ADMIN_FAILED = 'PERMISSION_COMPANY_SUPPER_ADMIN_FAILED';
export const PERMISSION_COMPANY_SUPPER_ADMIN_RESET = 'PERMISSION_COMPANY_SUPPER_ADMIN_RESET';

export const DELETE_COMPANY_SUPPER_ADMIN_REQUEST = 'DELETE_COMPANY_SUPPER_ADMIN_REQUEST';
export const DELETE_COMPANY_SUPPER_ADMIN_SUCCESS = 'DELETE_COMPANY_SUPPER_ADMIN_SUCCESS';
export const DELETE_COMPANY_SUPPER_ADMIN_FAILED = 'DELETE_COMPANY_SUPPER_ADMIN_FAILED';
export const DELETE_COMPANY_SUPPER_ADMIN_RESET = 'DELETE_COMPANY_SUPPER_ADMIN_RESET';

// users constants
export const USERS_SUPPER_ADMIN_REQUEST = 'USERS_SUPPER_ADMIN_REQUEST';
export const USERS_SUPPER_ADMIN_SUCCESS = 'USERS_SUPPER_ADMIN_SUCCESS';
export const USERS_SUPPER_ADMIN_FAILED = 'USERS_SUPPER_ADMIN_FAILED';
export const USERS_SUPPER_ADMIN_RESET = 'USERS_SUPPER_ADMIN_RESET';

export const GET_USER_SUPPER_ADMIN_REQUEST = 'GET_USER_SUPPER_ADMIN_REQUEST';
export const GET_USER_SUPPER_ADMIN_SUCCESS = 'GET_USER_SUPPER_ADMIN_SUCCESS';
export const GET_USER_SUPPER_ADMIN_FAILED = 'GET_USER_SUPPER_ADMIN_FAILED';
export const GET_USER_SUPPER_ADMIN_RESET = 'GET_USER_SUPPER_ADMIN_RESET';

export const DELETE_USER_SUPPER_ADMIN_REQUEST = 'DELETE_USER_SUPPER_ADMIN_REQUEST';
export const DELETE_USER_SUPPER_ADMIN_SUCCESS = 'DELETE_USER_SUPPER_ADMIN_SUCCESS';
export const DELETE_USER_SUPPER_ADMIN_FAILED = 'DELETE_USER_SUPPER_ADMIN_FAILED';
export const DELETE_USER_SUPPER_ADMIN_RESET = 'DELETE_USER_SUPPER_ADMIN_RESET';

// project constants
export const PROJECTS_SUPPER_ADMIN_REQUEST = 'PROJECTS_SUPPER_ADMIN_REQUEST';
export const PROJECTS_SUPPER_ADMIN_SUCCESS = 'PROJECTS_SUPPER_ADMIN_SUCCESS';
export const PROJECTS_SUPPER_ADMIN_FAILED = 'PROJECTS_SUPPER_ADMIN_FAILED';
export const PROJECTS_SUPPER_ADMIN_RESET = 'PROJECTS_SUPPER_ADMIN_RESET';

export const GET_PROJECT_SUPPER_ADMIN_REQUEST = 'GET_PROJECT_SUPPER_ADMIN_REQUEST';
export const GET_PROJECT_SUPPER_ADMIN_SUCCESS = 'GET_PROJECT_SUPPER_ADMIN_SUCCESS';
export const GET_PROJECT_SUPPER_ADMIN_FAILED = 'GET_PROJECT_SUPPER_ADMIN_FAILED';
export const GET_PROJECT_SUPPER_ADMIN_RESET = 'GET_PROJECT_SUPPER_ADMIN_RESET';

export const DELETE_PROJECT_SUPPER_ADMIN_REQUEST = 'DELETE_PROJECT_SUPPER_ADMIN_REQUEST';
export const DELETE_PROJECT_SUPPER_ADMIN_SUCCESS = 'DELETE_PROJECT_SUPPER_ADMIN_SUCCESS';
export const DELETE_PROJECT_SUPPER_ADMIN_FAILED = 'DELETE_PROJECT_SUPPER_ADMIN_FAILED';
export const DELETE_PROJECT_SUPPER_ADMIN_RESET = 'DELETE_PROJECT_SUPPER_ADMIN_RESET';