export const USERS_COMPANY_REQUEST = 'USERS_COMPANY_REQUEST';
export const USERS_COMPANY_SUCCESS = 'USERS_COMPANY_SUCCESS';
export const USERS_COMPANY_FAILED = 'USERS_COMPANY_FAILED';
export const USERS_COMPANY_RESET = 'USERS_COMPANY_RESET';

export const GET_USER_REQUEST = 'GET_USER_REQUEST';
export const GET_USER_SUCCESS = 'GET_USER_SUCCESS';
export const GET_USER_FAILED = 'GET_USER_FAILED';
export const GET_USER_RESET = 'GET_USER_RESET';

export const UPDATE_USER_REQUEST = 'UPDATE_USER_REQUEST';
export const UPDATE_USER_SUCCESS = 'UPDATE_USER_SUCCESS';
export const UPDATE_USER_FAILED = 'UPDATE_USER_FAILED';
export const UPDATE_USER_RESET = 'UPDATE_USER_RESET';

export const TOGGLE_STATUS_USER_REQUEST = 'TOGGLE_STATUS_USER_REQUEST';
export const TOGGLE_STATUS_USER_SUCCESS = 'TOGGLE_STATUS_USER_SUCCESS';
export const TOGGLE_STATUS_USER_FAILED = 'TOGGLE_STATUS_USER_FAILED';
export const TOGGLE_STATUS_USER_RESET = 'TOGGLE_STATUS_USER_RESET';

export const CREATE_USER_REQUEST = 'CREATE_USER_REQUEST';
export const CREATE_USER_SUCCESS = 'CREATE_USER_SUCCESS';
export const CREATE_USER_FAILED = 'CREATE_USER_FAILED';
export const CREATE_USER_RESET = 'CREATE_USER_RESET';

export const DELETE_USER_REQUEST = 'DELETE_USER_REQUEST';
export const DELETE_USER_SUCCESS = 'DELETE_USER_SUCCESS';
export const DELETE_USER_FAILED = 'DELETE_USER_FAILED';
export const DELETE_USER_RESET = 'DELETE_USER_RESET';
