name: REACT CICD

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: self-hosted
    timeout-minutes: 10

    strategy:
      matrix:
        node-version: [16.17.0]

    steps:
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
      - name: remove node_module
        run: sudo rm -rf /var/www/frontend/_work/easyIFU-client-side/easyIFU-client-side/node_modules

      - name: Install dependencies
        run: sudo npm i
  
      - name: Build project
        run: npm run build
