name: REACT CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: self-hosted
    timeout-minutes: 10

    strategy:
      matrix:
        node-version: [16.17.0]

    steps:
      - name: Install dependencies
        run: npm i --force
  
      - name: Build project
        run: npm run build

      - name: Restart Nginx
        run: sudo service nginx restart
